email_input_field = '[name="email"][data-qa-selector="form-control"]'
password_input_field = 'input[name="password"][data-qa-selector="password"]'
submit_button = 'button[type="submit"]'
login_error = '[data-qa-selector="help"][data-qa-selector-name="email"]'
confirm_email_section = '[data-qa-selector="section"]'
